### ISSUE TITLE
Error - Unknown @ rule: @-ms-keyframes

### ISSUE THREAD

**Issue by diggabyte** [CSSLint/csslint#295]
Introduced after this commit:
https://github.com/stubbornella/csslint/commit/e14628b270c59aef02de5c0c9d4e67adbc9793ac

Looks like the @-ms-keyframes prefix was accidentally overwritten with @-o-keyframes when fixing issue #286

I commented on the line that broke it.

**Comment by Bart76** [comment]
Closed? Strange. And Diggabyte's just question about backward compatibility remains completely unanswered... (Or is "stupidly neglected" perhaps a better term in this specific case?)

I just noticed that - after more than six years - this issue is still topical. I am confident that the CssLint behavior is incorrect. As I see it, a specific browser version has NOTHING to do with correct (historical) CSS analysis.

Or perhaps should I understand that targeting and using earlier versions of IE should not be taken seriously anymore? (Nowadays, that might be a fair subject of discussion, but six years ago when IE10 was just released?...)

And during the last six years, everybody who is/was related to the CssLint project seemed to pretend that this is quite fine. Otherwise, Diggabyte's question would have been satisfactory answered.

Seems that quality goes down the toilet on purpose here. Madness. Good luck with this project.
