### ISSUE TITLE
use "-webkit-image-set" its return error

### ISSUE THREAD

**Issue by wudizhenkunao** [CSSLint/csslint#608]
background-image: -webkit-image-set(url(../image/logo.jpg?v3) 1x, url(../image/logo2.png?v3) 2x);

**Comment by 18612790635** [comment]
o i have  the same error  flow

**Comment by frvge** [comment]
This is in the draft for 
https://drafts.csswg.org/css-images-3/#funcdef-image-set , but it's been removed in the final version ) https://www.w3.org/TR/css3-images/ ) . Currently, the support is only with a prefix. http://caniuse.com/#feat=css-image-set .

This is more a ticket for Parser-lib, but since it's not in the spec, I'm not sure if we'll add support for it. You can make another issue at https://github.com/CSSLint/parser-lib .
