### ISSUE TITLE
Is there an "official" fork?

### ISSUE THREAD

**Issue by reaktivo** [CSSLint/csslint#616]
This projects seems to be abandoned. Can we join efforts in a single repo? There seems to be a great amount of features being developed by some forks.

**Comment by stubbornella** [comment]
Which forks? I'll add collaborators to this repo.

**Comment by reaktivo** [comment]
Well, there's at least two nice pull requests that I would love to see in the csslint project, and would resolve a bunch of problems.

- Added Ignore Capability #564 
- Allow linting empty file #463

**Comment by bignimbus** [comment]
:+1:  but preferred solution would be for the admin to add maintainers to this repo

**Comment by Arcanemagus** [comment]
Just as some evidence that _something_ needs to be done, for the [linter-csslint](https://github.com/AtomLinter/linter-csslint) Atom package we have had to use an alternate fork until #605 and #606 are merged in here. I would absolutely _love_ to delete that fork and use the official repository again!

**Comment by stubbornella** [comment]
Can we use this thread to start proposing collaborators? We'll also need to put together a code of conduct since it will be less of a poorly run monarchy. ;) Maybe there is one we can borrow from another project?




One of the a11y projects I've contributed to requires rough consensus amongst collaborators and green tests to merge. That seems good to me.

**Comment by Arcanemagus** [comment]
Any takers? This project is looking rather abandoned currently...

**Comment by frvge** [comment]
There is more activity again so I'm closing this issue.
