### ISSUE TITLE
Including csslint.js causes "require is not defined" errors

### ISSUE THREAD

**Issue by paulmcfe** [CSSLint/csslint#666]
I've been using csslint.js in a CodeMirror project for several months without a problem. A few days ago, I started getting "Uncaught ReferenceError: require is not defined" messages. After some trial and error, I found that if I remove csslint.js, the errors go away. Here are my includes:

```html
<script src="http://htmlhint.com/js/htmlhint.js"></script>
<script src="http://csslint.net/js/csslint.js"></script>
<script src="js/lint/lint.js"></script>
<script src="js/lint/html-lint.js"></script>
<script src="js/lint/css-lint.js"></script>
<script src="js/spectrum.js"></script>
```

The errors:

![image](https://cloud.githubusercontent.com/assets/7156439/17020859/096fe602-4f12-11e6-89b6-f23b844d83c5.png)

Perhaps a recent commit is causing the error?

Cheers,
Paul

**Comment by XhmikosR** [comment]
Are you sure that's with v1.0.2?

**Comment by paulmcfe** [comment]
Yes. I'm linking directly to csslint.js on csslint.net. I also tried downloading v1.0.2 and including the local copy instead of the remote file, but I received the same errors.

**Comment by XhmikosR** [comment]
Try 1.0.1. Also do not rely on our website for your assets. It's bad
practice.

**Comment by paulmcfe** [comment]
Understood, thanks. 1.0.1 did not solve the problem. See also this CodeMirror issue, which seems to be the same problem:

https://github.com/codemirror/CodeMirror/commit/8a1dd1604974840fe69163f958ad204010442aea

**Comment by XhmikosR** [comment]
There nothing I can do since the Web  build works on our site.

You are welcome to make a pull request and CC me if you find fix. Have a
look at parser lib too.

**Comment by orionlee** [comment]
I ran into the same problem. It is in the generated [dist/csslint.js](https://github.com/CSSLint/csslint/blob/v1.0.2/dist/csslint.js#L25) , it defines dummy module and exports in global scope, rather than inside `CSSLint` definition.

It breaks integration with CodeMirror (and possibly other web js lib supporting module loading) because the dummy module and exports make CodeMirror mistakenly believe it is loaded in CommonJS environment.

One way to fix it is to change the [Gruntefile](https://github.com/CSSLint/csslint/blob/v1.0.2/Gruntfile.js#L64) and move the dummy module and exports inside `CSSLint` definition.

Thought?

**Comment by XhmikosR** [comment]
@orionlee: Please submit a PR and CC me.
